// Books Index Database
const booksIndex = {
    // Single volume books (direct files)
    "single": [
        {
            name: "المسند للشافعي",
            file: "https://raw.githubusercontent.com/saadhusainn/sijjeen02/main/11.pdf",
            publisher: "دار الكتب العلمية",
            language: "العربية",
            type: "single"
        },
        {
            name:"صحيح البخاري",
            file:"https://raw.githubusercontent.com/Saadhusainn/sijjeen03.1/main/25.pdf",
            publisher:"دار ابن كثير",
            language:"العربية",
            type:"single"
        },
         { 
            name: "الأدب المفرد - ت عبد الباقي", 
            file: "https://raw.githubusercontent.com/Saadhusainn/sijjeen04/main/33.pdf",
            publisher: "دار البشائر الإسلامية",
            language: "العربية",
            type: "single"
        },
        {
            name:"مسند الدارمي - ت الزهراني",
            file:"https://raw.githubusercontent.com/Saadhusainn/sijjeen04/main/36.pdf",
            publisher:"N/A",
            language:"العربية",
            type:"single"
        },
        {
            name: "مسند ابن الجعد",
            file: "https://raw.githubusercontent.com/saadhusainn/sijjeen02/main/10.pdf",
            publisher: "دار الكتب العلمية",
            language: "العربية",
            type: "single"
        },
        {
            name:"موطأ مالك رواية يحيى - ت عبد الباقي",
            file:"https://raw.githubusercontent.com/Saadhusainn/sijjeen04/main/37.pdf",
            publisher:"دار أحياء التراث العربي",
            language:"العربية",
            type:"single"
        },
        {
            name:"علل الترمذي الكبير",
            file:"https://raw.githubusercontent.com/Saadhusainn/sijjeen04/tree/main/35.pdf",
            publisher:"مكتبة النهضة العربية",
            language:"العربية",
            type:"single"
        }
    ],
    
    // Multi-volume books (with custom volume names)
    "multi": [
        { 
            name: "المصنف لعبد الرزاق - ت الأعظمي", 
            type: "multi",
            publisher: "المكتبة الإسلامي",
            language: "العربية",
            volumes: [
                { name: "0", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen02/main/19/miar00.pdf" },
                { name: "01", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen02/main/19/miar01.pdf" },
                { name: "01p", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen02/main/19/miar01p.pdf" },
                { name: "02", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen02/main/19/miar02.pdf" },
                { name: "02p", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen02/main/19/miar02p.pdf" },
                { name: "03", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen02/main/19/miar03.pdf" },
                { name: "03p", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen02/main/19/miar03p.pdf" },
                { name: "04", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen02/main/19/miar04.pdf" },
                { name: "04p", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen02/main/19/miar04p.pdf" },
                { name: "05", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen02/main/19/miar05.pdf" },
                { name: "05p", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen02/main/19/miar05p.pdf" },
                { name: "06", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen02/main/19/miar06.pdf" },
                { name: "06p", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen02/main/19/miar06p.pdf" },
                { name: "07", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen02/main/19/miar07.pdf" },
                { name: "07p", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen02/main/19/miar07p.pdf" },
                { name: "08", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen02/main/19/miar08.pdf" },
                { name: "08p", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen02/main/19/miar08p.pdf" },
                { name: "09", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen02/main/19/miar09.pdf" },
                { name: "09p", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen02/main/19/miar09p.pdf" },
                { name: "10", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen02/main/19/miar10.pdf" },
                { name: "10p", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen02/main/19/miar10p.pdf" },
                { name: "11", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen02/main/19/miar11.pdf" },
                { name: "11p", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen02/main/19/miar11p.pdf" },
                { name: "12", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen02/main/19/miar12.pdf" },
                { name: "Missing Part", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen02/main/19/missing_part.pdf" }
            ],
            isDropdownOpen: false
        },
        { 
            name: "مسند أبي يعلى الموصيلي", 
            type: "multi",
            publisher: "دار المامون للتراث",
            language: "العربية",
            volumes: [
                { name: "00", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen02/main/21/mayala00.pdf" },
                { name: "01", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen02/main/21/mayala01.pdf" },
                { name: "01p", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen02/main/21/mayala01p.pdf" },
                { name: "02", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen02/main/21/mayala02.pdf" },
                { name: "03", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen02/main/21/mayala03.pdf" },
                { name: "04", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen02/main/21/mayala04.pdf" },
                { name: "05", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen02/main/21/mayala05.pdf" },
                { name: "06", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen02/main/21/mayala06.pdf" },
                { name: "07", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen02/main/21/mayala07.pdf" },
                { name: "08", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen02/main/21/mayala08.pdf" },
                { name: "09", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen02/main/21/mayala09.pdf" },
                { name: "10", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen02/main/21/mayala10.pdf" },
                { name: "11", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen02/main/21/mayala11.pdf" },
                { name: "12", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen02/main/21/mayala12.pdf" },
                { name: "13", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen02/main/21/mayala13.pdf" },
                { name: "14", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen02/main/21/mayala014.pdf" }
            ],
            isDropdownOpen: false
        },
        { 
            name: "المعجم الكبير للطبراني", 
            type: "multi",
            publisher: "مكتبة ابن تيمية",
            language: "العربية",
            volumes: [
                { name: "0", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen01/main/2/mtk00.pdf" },
                { name: "1", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen01/main/2/mtk01.pdf" },
                { name: "2", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen01/main/2/mtk02.pdf" },
                { name: "3", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen01/main/2/mtk03.pdf" },
                { name: "3p", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen01/main/2/mtk03p.pdf" },
                { name: "4", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen01/main/2/mtk04.pdf" },
                { name: "5", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen01/main/2/mtk05.pdf" },
                { name: "6", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen01/main/2/mtk06.pdf" },
                { name: "7", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen01/main/2/mtk08.pdf" },
                { name: "8", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen01/main/2/mtk09.pdf" },
                { name: "9", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen01/main/2/mtk09p.pdf" },
                { name: "9p", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen01/main/2/mtk09p.pdf" },
                { name: "10", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen01/main/2/mtk10.pdf" },
                { name: "11", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen01/main/2/mtk11.pdf" },
                { name: "12", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen01/main/2/mtk12.pdf" },
                { name: "13", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen01/main/2/mtk13.pdf" },
                { name: "13_1", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen01/main/2/mtk13_1.pdf" },
                { name: "14", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen01/main/2/mtk14.pdf" },
                { name: "17", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen01/main/2/mtk17.pdf" },
                { name: "18", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen01/main/2/mtk18.pdf" },
                { name: "19", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen01/main/2/mtk19.pdf" },
                { name: "19p", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen01/main/2/mtk019p.pdf" },
                { name: "20", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen01/main/2/mtk20.pdf" },
                { name: "21", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen01/main/2/mtk21.pdf" },
                { name: "22", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen01/main/2/mtk22.pdf" },
                { name: "23", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen01/main/2/mtk23.pdf" },
                { name: "24", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen01/main/2/mtk24.pdf" },
                { name: "25", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen01/main/2/mtk25.pdf" },
            ],
            isDropdownOpen: false
        },
        { 
            name: "المصنف لابن أبي شيبة ت الشثري", 
            type: "multi",
            publisher: "دار كنوز",
            language: "العربية",
            volumes: [
                { name: "0", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen01/main/7/shaybah00.pdf" },
                { name: "1", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen01/main/7/shaybah01.pdf" },
                { name: "2", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen01/main/7/shaybah02.pdf" },
                { name: "3", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen01/main/7/shaybah03.pdf" },
                { name: "4", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen01/main/7/shaybah04.pdf" },
                { name: "5", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen01/main/7/shaybah05.pdf" },
                { name: "6", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen01/main/7/shaybah06.pdf" },
                { name: "7", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen01/main/7/shaybah07.pdf" },
                { name: "8", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen01/main/7/shaybah08.pdf" },
                { name: "9", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen01/main/7/shaybah09.pdf" },
                { name: "10", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen01/main/7/shaybah10.pdf" },
                { name: "11", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen01/main/7/shaybah11.pdf" },
                { name: "12", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen01/main/7/shaybah12.pdf" },
                { name: "13", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen01/main/7/shaybah13.pdf" },
                { name: "14", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen01/main/7/shaybah14.pdf" },
                { name: "15", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen01/main/7/shaybah15.pdf" },
                { name: "16", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen01/main/7/shaybah16.pdf" },
                { name: "17", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen01/main/7/shaybah17.pdf" },
                { name: "18", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen01/main/7/shaybah18.pdf" },
                { name: "19", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen01/main/7/shaybah19.pdf" },
                { name: "20", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen01/main/7/shaybah20.pdf" },
                { name: "21", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen01/main/7/shaybah21.pdf" },
                { name: "22", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen01/main/7/shaybah22.pdf" },
                { name: "23", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen01/main/7/shaybah23.pdf" },
                { name: "24", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen01/main/7/shaybah24.pdf" },
                { name: "25", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen01/main/7/shaybah25.pdf" }
            ],
            isDropdownOpen: false
        },
        { 
            name: "السنن الكبرى للنسائي", 
            type: "multi",
            publisher: "المكتبة الرسالة",
            language: "العربية",
           volumes: [
    { name: "1", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen01/main/4/snk01.pdf" },
    { name: "2", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen01/main/4/snk02.pdf" },
    { name: "3", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen01/main/4/snk03.pdf" },
    { name: "4", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen01/main/4/snk04.pdf" },
    { name: "5", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen01/main/4/snk05.pdf" },
    { name: "6", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen01/main/4/snk06.pdf" },
    { name: "7", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen01/main/4/snk07.pdf" },
    { name: "8", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen01/main/4/snk08.pdf" },
    { name: "9", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen01/main/4/snk09.pdf" },
    { name: "10", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen01/main/4/snk10.pdf" },
    { name: "11", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen01/main/4/snk11.pdf" },
    { name: "12", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen01/main/4/snk12.pdf" }
],
            isDropdownOpen: false
        },
        { 
            name: "المعجم الصغير للطبراني", 
            type: "multi",
            publisher: "دار الكتب العلمية",
            language: "العربية",
            volumes: [
                { name: "0", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen01/main/3/mst0.pdf" },
                { name: "1", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen01/main/3/mst1.pdf" },
                { name: "2", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen01/main/3/mst2.pdf" }
            ],
            isDropdownOpen: false
        },
        { 
            name: "المعجم الأوسط للطبراني", 
            type: "multi",
            publisher: "دار الحرمين",
            language: "العربية",
           volumes: [
    { name: "0", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen01/main/1/mat00.pdf" },
    { name: "1", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen01/main/1/mat01.pdf" },
    { name: "2", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen01/main/1/mat02.pdf" },
    { name: "3", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen01/main/1/mat03.pdf" },
    { name: "4", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen01/main/1/mat04.pdf" },
    { name: "5", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen01/main/1/mat05.pdf" },
    { name: "6", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen01/main/1/mat06.pdf" },
    { name: "7", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen01/main/1/mat07.pdf" },
    { name: "8", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen01/main/1/mat08.pdf" },
    { name: "9", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen01/main/1/mat09.pdf" },
    { name: "10", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen01/main/1/mat10.pdf" }
],
            isDropdownOpen: false
        },
        { 
            name: "مسند أبي داود الطيالسي", 
            type: "multi",
            publisher: "دار هجر",
            language: "العربية",
            volumes: [
                { name: "0", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen02/main/12/madt0.pdf" },
                { name: "1", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen02/main/12/madt1.pdf" },
                { name: "1p", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen02/main/12/madt1p.pdf" },
                { name: "2", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen02/main/12/madt2.pdf" },
                { name: "3", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen02/main/12/madt3.pdf" },
                { name: "4", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen02/main/12/madt4.pdf" },
            ],
            isDropdownOpen: false
        },
        { 
            name: "مسند أحمد ت شاكر", 
            type: "multi",
            publisher: "دار الحديث",
            language: "العربية",
           volumes: [
    { name: "0", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen01/main/8/musnda00.pdf" },
    { name: "1", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen01/main/8/musnda01.pdf" },
    { name: "2", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen01/main/8/musnda02.pdf" },
    { name: "3", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen01/main/8/musnda03.pdf" },
    { name: "4", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen01/main/8/musnda04.pdf" },
    { name: "5", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen01/main/8/musnda05.pdf" },
    { name: "6", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen01/main/8/musnda06.pdf" },
    { name: "7", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen01/main/8/musnda07.pdf" },
    { name: "8", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen01/main/8/musnda08.pdf" },
    { name: "9", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen01/main/8/musnda09.pdf" },
    { name: "10", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen01/main/8/musnda10.pdf" },
    { name: "11", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen01/main/8/musnda11.pdf" },
    { name: "12", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen01/main/8/musnda12.pdf" },
    { name: "13", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen01/main/8/musnda13.pdf" },
    { name: "14", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen01/main/8/musnda14.pdf" },
    { name: "15", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen01/main/8/musnda15.pdf" },
    { name: "16", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen01/main/8/musnda16.pdf" },
    { name: "17", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen01/main/8/musnda17.pdf" },
    { name: "18", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen01/main/8/musnda18.pdf" }
],
            isDropdownOpen: false
        },
        { 
            name: "البحر الزخار المعروف بمسند البزار", 
            type: "multi",
            publisher: "مكتبة العلوم",
            language: "العربية",
           volumes: [
    { name: "0", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen01/main/5/musbaz00.pdf" },
    { name: "1", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen01/main/5/musbaz01.pdf" },
    { name: "2", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen01/main/5/musbaz02.pdf" },
    { name: "3", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen01/main/5/musbaz03.pdf" },
    { name: "4", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen01/main/5/musbaz04.pdf" },
    { name: "5", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen01/main/5/musbaz05.pdf" },
    { name: "6", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen01/main/5/musbaz06.pdf" },
    { name: "7", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen01/main/5/musbaz07.pdf" },
    { name: "8", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen01/main/5/musbaz08.pdf" },
    { name: "9", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen01/main/5/musbaz09.pdf" },
    { name: "10", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen01/main/5/musbaz10.pdf" },
    { name: "11", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen01/main/5/musbaz11.pdf" },
    { name: "12", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen01/main/5/musbaz12.pdf" },
    { name: "13", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen01/main/5/musbaz13.pdf" },
    { name: "14", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen01/main/5/musbaz14.pdf" },
    { name: "15", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen01/main/5/musbaz15.pdf" }
],
            isDropdownOpen: false
        },
        { 
            name: "المستدرك على الصحيحين للحاكم", 
            type: "multi",
            publisher: "دار الكتب العلمية",
            language: "العربية",
            volumes: [
    { name: "0", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen02/main/18/00.pdf" },
    { name: "1", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen02/main/18/01.pdf" },
    { name: "2", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen02/main/18/02.pdf" },
    { name: "3", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen02/main/18/03.pdf" },
    { name: "4", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen02/main/18/04.pdf" },
    { name: "5", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen02/main/18/05.pdf" }
],
            isDropdownOpen: false
        },
        { 
            name: "شعب الإيمان ت الزغلول", 
            type: "multi",
            publisher: "دار الكتب العلمية",
            language: "العربية",
           volumes: [
    { name: "00", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen02/main/15/gshe_elmiya00.pdf" },
    { name: "01", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen02/main/15/gshe_elmiya01.pdf" },
    { name: "02", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen02/main/15/gshe_elmiya02.pdf" },
    { name: "03", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen02/main/15/gshe_elmiya03.pdf" },
    { name: "04", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen02/main/15/gshe_elmiya04.pdf" },
    { name: "05", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen02/main/15/gshe_elmiya05.pdf" },
    { name: "06", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen02/main/15/gshe_elmiya06.pdf" },
    { name: "07", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen02/main/15/gshe_elmiya07.pdf" },
    { name: "08", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen02/main/15/gshe_elmiya08.pdf" },
    { name: "09", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen02/main/15/gshe_elmiya09.pdf" }
],
            isDropdownOpen: false
        },
        { 
            name: "السنن الكبرى للبيهقى", 
            type: "multi",
            publisher: "دار الكتب العلمية",
            language: "العربية",
           volumes: [
    { name: "00", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen02/main/17/skb00.pdf" },
    { name: "01", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen02/main/17/skb01.pdf" },
    { name: "02", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen02/main/17/skb02.pdf" },
    { name: "03", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen02/main/17/skb03.pdf" },
    { name: "04", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen02/main/17/skb04.pdf" },
    { name: "05", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen02/main/17/skb05.pdf" },
    { name: "06", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen02/main/17/skb06.pdf" },
    { name: "07", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen02/main/17/skb07.pdf" },
    { name: "08", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen02/main/17/skb08.pdf" },
    { name: "09", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen02/main/17/skb09.pdf" },
    { name: "10", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen02/main/17/skb10.pdf" },
    { name: "11", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen02/main/17/skb11.pdf" }
],
            isDropdownOpen: false
        },
         { 
            name: "دلائل النبوة للذهبى", 
            type: "multi",
            publisher: "دار الكتب العلمية",
            language: "العربية",
           volumes: [
    { name: "0", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen01/main/6/dalail0.pdf" },
    { name: "1", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen01/main/6/dalail1.pdf" },
    { name: "2", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen01/main/6/dalail2.pdf" },
    { name: "3", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen01/main/6/dalail3.pdf" },
    { name: "4", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen01/main/6/dalail4.pdf" },
    { name: "5", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen01/main/6/dalail5.pdf" },
    { name: "6", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen01/main/6/dalail6.pdf" }
],
            isDropdownOpen: false
        },
        { 
            name: "صحيح ابن حبان", 
            type: "multi",
            publisher: "دار ابن حزم",
            language: "العربية",
            volumes: [
    { name: "المجلد 1", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen02/main/13/المجلد 1.pdf" },
    { name: "المجلد 2", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen02/main/13/المجلد 2.pdf" },
    { name: "المجلد 3", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen02/main/13/المجلد 3.pdf" },
    { name: "المجلد 4", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen02/main/13/المجلد 4.pdf" },
    { name: "المجلد 5", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen02/main/13/المجلد 5.pdf" },
    { name: "المجلد 6", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen02/main/13/المجلد 6.pdf" },
    { name: "المجلد 7", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen02/main/13/المجلد 7.pdf" },
    { name: "المجلد 8", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen02/main/13/المجلد 8.pdf" }
],
            isDropdownOpen: false
        },
        { 
            name: "صحيح ابن خزيمة", 
            type: "multi",
            publisher: "مكتبة الإسلامي",
            language: "العربية",
            volumes: [
    { name: "0", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen02/main/14/shuzaima0.pdf" },
    { name: "1", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen02/main/14/shuzaima1.pdf" },
    { name: "2", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen02/main/14/shuzaima2.pdf" },
    { name: "3", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen02/main/14/shuzaima3.pdf" },
    { name: "4", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen02/main/14/shuzaima4.pdf" }
],
            isDropdownOpen: false
        },
        { 
            name: "مسند الروياني", 
            type: "multi",
            publisher: "مؤسسة القرطبه",
            language: "العربية",
           volumes: [
    { name: "00", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen02/main/9/Musnad_Ruyani00.pdf" },
    { name: "01", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen02/main/9/Musnad_Ruyani01.pdf" },
    { name: "02", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen02/main/9/Musnad_Ruyani02.pdf" },
    { name: "03", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen02/main/9/Musnad_Ruyani03.pdf" },
    { name: "04", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen02/main/9/Musnad_Ruyani04.pdf" }
],
            isDropdownOpen: false
        },
        { 
            name: "سنن الدرقطني", 
            type: "multi",
            publisher: "مؤسسة الرسالة",
            language: "العربية",
           volumes: [
    { name: "0", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen02/main/16/sdark0.pdf" },
    { name: "1", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen02/main/16/sdark1.pdf" },
    { name: "2", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen02/main/16/sdark2.pdf" },
    { name: "3", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen02/main/16/sdark3.pdf" },
    { name: "4", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen02/main/16/sdark4.pdf" },
    { name: "5", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen02/main/16/sdark5.pdf" },
    { name: "6", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen02/main/16/sdark6.pdf" }
],
            isDropdownOpen: false
        },
        { 
            name: "حلية الأولياء", 
            type: "multi",
            publisher: "دار فكر",
            language: "العربية",
         volumes: [
    { name: "0", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen02/main/20/حلية الأولياء وطبقات الأصفياء.pdf" },
    { name: "1", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen02/main/20/حلية الأولياء وطبقات الأصفياء ـ الجز 1.pdf" },
    { name: "2", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen02/main/20/حلية الأولياء وطبقات الأصفياء ـ الجز 2.pdf" },
    { name: "3", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen02/main/20/حلية الأولياء وطبقات الأصفياء ـ الجز 3.pdf" },
    { name: "4", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen02/main/20/حلية الأولياء وطبقات الأصفياء ـ الجز 4.pdf" },
    { name: "5", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen02/main/20/حلية الأولياء وطبقات الأصفياء ـ الجز 5.pdf" },
    { name: "6", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen02/main/20/حلية الأولياء وطبقات الأصفياء ـ الجز 6.pdf" },
    { name: "7", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen02/main/20/حلية الأولياء وطبقات الأصفياء ـ الجز 7.pdf" },
    { name: "8", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen02/main/20/حلية الأولياء وطبقات الأصفياء ـ الجز 8.pdf" },
    { name: "9", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen02/main/20/حلية الأولياء وطبقات الأصفياء ـ الجز 9.pdf" },
    { name: "10", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen02/main/20/حلية الأولياء وطبقات الأصفياء ـ الجز 10.pdf" }
],
            isDropdownOpen: false
        },
        { 
            name: "سنن الترمذي", 
            type: "multi",
            publisher: "دار التأصيل",
            language: "العربية",
          volumes: [
    { name: "1", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen04/main/31/1.pdf" },
    { name: "2", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen04/main/31/2.pdf" },
    { name: "3", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen04/main/31/3.pdf" },
    { name: "4", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen04/main/31/4.pdf" },
    { name: "5", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen04/main/31/5.pdf" }
],
            isDropdownOpen: false
        },
        { 
            name: "سنن الترمذي - شعيب الأرنؤوط", 
            type: "multi",
            publisher: "دار الرسالة العالمية",
            language: "العربية",
           volumes: [
    { name: "00", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen04/main/32/jt00.pdf" },
    { name: "01", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen04/main/32/jt01.pdf" },
    { name: "02", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen04/main/32/jt02.pdf" },
    { name: "03", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen04/main/32/jt03.pdf" },
    { name: "04", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen04/main/32/jt04.pdf" },
    { name: "05", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen04/main/32/jt05.pdf" },
    { name: "06", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen04/main/32/jt06.pdf" }
],
            isDropdownOpen: false
        },
        { 
            name: "الطبقات الكبرى لابن سعد", 
            type: "multi",
            publisher: "مكتبة الخانجي",
            language: "العربية",
           volumes: [
    { name: "00", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen04/main/34/A66aba9at_00.pdf" },
    { name: "01", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen04/main/34/A66aba9at_01.pdf" },
    { name: "02", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen04/main/34/A66aba9at_02.pdf" },
    { name: "03", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen04/main/34/A66aba9at_03.pdf" },
    { name: "04", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen04/main/34/A66aba9at_04.pdf" },
    { name: "05", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen04/main/34/A66aba9at_05.pdf" },
    { name: "06", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen04/main/34/A66aba9at_06.pdf" },
    { name: "07", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen04/main/34/A66aba9at_07.pdf" },
    { name: "08", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen04/main/34/A66aba9at_08.pdf" },
    { name: "09", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen04/main/34/A66aba9at_09.pdf" },
    { name: "10", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen04/main/34/A66aba9at_10.pdf" },
    { name: "11", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen04/main/34/A66aba9at_11.pdf" }
],
            isDropdownOpen: false
        },
        { 
            name: "سنن أبي داود - شعيب الأرنؤوط", 
            type: "multi",
            publisher: "دار الرسالة الاعلامية",
            language: "العربية",
            volumes: [
    { name: "0", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen03.1/main/22/0.pdf" },
    { name: "1", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen03.1/main/22/1.pdf" },
    { name: "2", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen03.1/main/22/2.pdf" },
    { name: "3", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen03.1/main/22/3.pdf" },
    { name: "4", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen03.1/main/22/4.pdf" },
    { name: "5", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen03.1/main/22/5.pdf" },
    { name: "6", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen03.1/main/22/6.pdf" },
    { name: "7", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen03.1/main/22/7.pdf" }
],
            isDropdownOpen: false
        },
        { 
            name: "الترغيب الترهيب", 
            type: "multi",
            publisher: "دار الكتب العلمية ",
            language: "العربية",
            volumes: [
    { name: "0", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen03.1/main/23/0.pdf" },
    { name: "1", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen03.1/main/23/1.pdf" },
    { name: "2", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen03.1/main/23/2.pdf" },
    { name: "3", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen03.1/main/23/3.pdf" },
    { name: "4", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen03.1/main/23/4.pdf" },
    { name: "مقدمة", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen03.1/main/23/مقدمة.pdf" }
],
            isDropdownOpen: false
        },
        { 
            name: "سنن ابن ماجه", 
            type: "multi",
            publisher: "دار جيل",
            language: "العربية",
           volumes: [
    { name: "00", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen03.1/main/25/Sunan_Ibn_Majah_Bashar00.pdf" },
    { name: "01", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen03.1/main/25/Sunan_Ibn_Majah_Bashar01.pdf" },
    { name: "02", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen03.1/main/25/Sunan_Ibn_Majah_Bashar02.pdf" },
    { name: "03", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen03.1/main/25/Sunan_Ibn_Majah_Bashar03.pdf" },
    { name: "04", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen03.1/main/25/Sunan_Ibn_Majah_Bashar04.pdf" },
    { name: "05", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen03.1/main/25/Sunan_Ibn_Majah_Bashar05.pdf" },
    { name: "06", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen03.1/main/25/Sunan_Ibn_Majah_Bashar06.pdf" }
],
            isDropdownOpen: false
        },
        { 
            name: "مسند إسحاق بن راهوايه", 
            type: "multi",
            publisher: "مكتبة الإيمان",
            language: "العربية",
            volumes: [
    { name: "0", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen03.1/main/26/misaac0.pdf" },
    { name: "1", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen03.1/main/26/misaac1.pdf" },
    { name: "2 & 3", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen03.1/main/26/misaac2-3.pdf" },
    { name: "4", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen03.1/main/26/misaac4.pdf" },
    { name: "5", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen03.1/main/26/misaac5.pdf" }
],
            isDropdownOpen: false
        },
        { 
            name: "مستخرج أبي عوانة", 
            type: "multi",
            publisher: "الجامعة الإسلامية",
            language: "العربية",
            volumes: [
                { name: "00", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen03.1/main/28/00_000000.pdf"},
                { name: "1-1", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen03.1/main/28/00_146801-1.pdf"},
                { name: "1-2", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen03.1/main/28/00_146801-2.pdf"},
    { name: "01", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen03.1/main/28/01_146802.pdf" },
    { name: "02", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen03.1/main/28/02_146803.pdf" },
    { name: "03", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen03.1/main/28/03_146804.pdf" },
    { name: "04", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen03.1/main/28/04_146805.pdf" },
    { name: "05", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen03.1/main/28/05_146806.pdf" },
    { name: "06", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen03.1/main/28/06_146807.pdf" },
    { name: "07", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen03.1/main/28/07_146808.pdf" },
    { name: "08", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen03.1/main/28/08_146809.pdf" },
    { name: "09", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen03.1/main/28/09_146810.pdf" },
    { name: "10", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen03.1/main/28/10_146811.pdf" },
    { name: "11", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen03.1/main/28/11_146812.pdf" },
    { name: "12", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen03.1/main/28/12_146813.pdf" },
    { name: "13", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen03.1/main/28/13_146814.pdf" },
    { name: "14", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen03.1/main/28/14_146815.pdf" },
    { name: "15", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen03.1/main/28/15_146816.pdf" },
    { name: "16", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen03.1/main/28/16_146817.pdf" },
    { name: "17", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen03.1/main/28/17_146818.pdf" },
    { name: "18", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen03.1/main/28/18_146819.pdf" },
    { name: "19", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen03.1/main/28/19_146820.pdf" },
    { name: "20", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen03.1/main/28/20_146821.pdf" },
    { name: "21", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen03.1/main/28/21.pdf" },
    { name: "22", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen03.1/main/28/22.pdf" }
],
            isDropdownOpen: false
        },
        { 
            name: "مجمع الزوائد", 
            type: "multi",
            publisher: "دار الكتاب العربي",
            language: "العربية",
           volumes: [
    { name: "1", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen04/main/38/مجمع الزوائد نور الدين علي الهيثمي ج1.pdf" },
    { name: "2", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen04/main/38/مجمع الزوائد نور الدين علي الهيثمي ج2.pdf" },
    { name: "3", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen04/main/38/مجمع الزوائد نور الدين علي الهيثمي ج3.pdf" },
    { name: "4", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen04/main/38/مجمع الزوائد نور الدين علي الهيثمي ج4.pdf" },
    { name: "5", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen04/main/38/مجمع الزوائد نور الدين علي الهيثمي ج5.pdf" },
    { name: "6", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen04/main/38/مجمع الزوائد نور الدين علي الهيثمي ج6.pdf" },
    { name: "7", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen04/main/38/مجمع الزوائد نور الدين علي الهيثمي ج7.pdf" },
    { name: "8", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen04/main/38/مجمع الزوائد نور الدين علي الهيثمي ج8.pdf" },
    { name: "9", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen04/main/38/مجمع الزوائد نور الدين علي الهيثمي ج9.pdf" },
    { name: "10", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen04/main/38/مجمع الزوائد نور الدين علي الهيثمي ج10.pdf" }
],
            isDropdownOpen: false
        },
        { 
            name: "عون المعبود شرح سنن أبي داود", 
            type: "multi",
            publisher: "دار الكتب العلمية",
            language: "العربية",
            volumes: [
    { name: "01", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen04/main/39/01_23895.pdf" },
    { name: "02", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen04/main/39/02_23896.pdf" },
    { name: "03", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen04/main/39/03_23897.pdf" },
    { name: "04", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen04/main/39/04_23898.pdf" },
    { name: "05", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen04/main/39/05_23899.pdf" },
    { name: "06", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen04/main/39/06_23900.pdf" },
    { name: "07", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen04/main/39/07_23901.pdf" },
    { name: "08", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen04/main/39/08_23902.pdf" },
    { name: "09", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen04/main/39/09_23903.pdf" },
    { name: "10", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen04/main/39/10_23904.pdf" },
    { name: "11", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen04/main/39/11_23905.pdf" },
    { name: "12", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen04/main/39/12_23906.pdf" },
    { name: "13", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen04/main/39/13_23907.pdf" },
    { name: "14", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen04/main/39/14_23908.pdf" },
    { name: "15", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen04/main/39/15_23909.pdf" },
    { name: "16", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen04/main/39/16_23910.pdf" }
],
            isDropdownOpen: false
        },
        { 
            name: "فيض الباري على صحيح البخاري", 
            type: "multi",
            publisher: "دار الكتب العلمية",
            language: "العربية",
            volumes: [
    { name: "1", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen04/main/40/فيض الباري على صحيح البخاري مع حاشية البدر الساري جلد 1.pdf" },
    { name: "2", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen04/main/40/فيض الباري على صحيح البخاري مع حاشية البدر الساري جلد 2.pdf" },
    { name: "3", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen04/main/40/فيض الباري على صحيح البخاري مع حاشية البدر الساري جلد 3.pdf" },
    { name: "4", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen04/main/40/فيض الباري على صحيح البخاري مع حاشية البدر الساري جلد 4.pdf" },
    { name: "5", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen04/main/40/فيض الباري على صحيح البخاري مع حاشية البدر الساري جلد 5.pdf" },
    { name: "6", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen04/main/40/فيض الباري على صحيح البخاري مع حاشية البدر الساري جلد 6.pdf" }
],
            isDropdownOpen: false
        },
        { 
            name: "معالم السنن للخطابي", 
            type: "multi",
            publisher: "N/A",
            language: "العربية",
            volumes: [
    { name: "0", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen04/main/41/ms0.pdf" },
    { name: "1", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen04/main/41/ms1.pdf" },
    { name: "2", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen04/main/41/ms2.pdf" },
    { name: "3", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen04/main/41/ms3.pdf" },
    { name: "4", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen04/main/41/ms4.pdf" }
],
            isDropdownOpen: false
        },
        { 
            name: "مرقاة المفاتيح شرح مشكاة المصابيح ", 
            type: "multi",
            publisher: "دار الكتب العلمية ",
            language: "العربية",
            volumes: [
    { name: "00", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen04/main/42/mmsmm00.pdf" },
    { name: "01", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen04/main/42/mmsmm01.pdf" },
    { name: "02", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen04/main/42/mmsmm02.pdf" },
    { name: "03", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen04/main/42/mmsmm03.pdf" },
    { name: "04", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen04/main/42/mmsmm04.pdf" },
    { name: "05", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen04/main/42/mmsmm05.pdf" },
    { name: "06", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen04/main/42/mmsmm06.pdf" },
    { name: "07", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen04/main/42/mmsmm07.pdf" },
    { name: "08", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen04/main/42/mmsmm08.pdf" },
    { name: "09", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen04/main/42/mmsmm09.pdf" },
    { name: "10", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen04/main/42/mmsmm10.pdf" },
    { name: "11", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen04/main/42/mmsmm11.pdf" },
    { name: "12", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen04/main/42/mmsmm12.pdf" }
],
            isDropdownOpen: false
        },
        { 
            name: "فتح الباري لابن رجب الحنبلي", 
            type: "multi",
            publisher: "مكتبة الغرباء الأثرية",
            language: "العربية",
           volumes: [
    { name: "00", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen05.1/main/45/fbir00.pdf" },
    { name: "01", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen05.1/main/45/fbir01.pdf" },
    { name: "02", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen05.1/main/45/fbir02.pdf" },
    { name: "03", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen05.1/main/45/fbir03.pdf" },
    { name: "04", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen05.1/main/45/fbir04.pdf" },
    { name: "05", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen05.1/main/45/fbir05.pdf" },
    { name: "06", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen05.1/main/45/fbir06.pdf" },
    { name: "07", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen05.1/main/45/fbir07.pdf" },
    { name: "08", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen05.1/main/45/fbir08.pdf" },
    { name: "09", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen05.1/main/45/fbir09.pdf" },
    { name: "10", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen05.1/main/45/fbir10.pdf" }
],
            isDropdownOpen: false
        },
        { 
            name: "إرشاد الساري شرح صحيح البخاري - ط دار الكتب العلمية", 
            type: "multi",
            publisher: "دار الكتب العلمية",
            language: "العربية",
           volumes: [
    { name: "0", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen05.1/main/47/إرشاد الساري لشرح صحيح البخاري ، الجز 0.pdf" },
    { name: "1", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen05.1/main/47/إرشاد الساري لشرح صحيح البخاري ، الجز 1.pdf" },
    { name: "2", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen05.1/main/47/إرشاد الساري لشرح صحيح البخاري ، الجز 2.pdf" },
    { name: "3", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen05.1/main/47/إرشاد الساري لشرح صحيح البخاري ، الجز 3.pdf" },
    { name: "4", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen05.1/main/47/إرشاد الساري لشرح صحيح البخاري ، الجز 4.pdf" },
    { name: "5", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen05.1/main/47/إرشاد الساري لشرح صحيح البخاري ، الجز 5.pdf" },
    { name: "6", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen05.1/main/47/إرشاد الساري لشرح صحيح البخاري ، الجز 6.pdf" },
    { name: "7", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen05.1/main/47/إرشاد الساري لشرح صحيح البخاري ، الجز 7.pdf" },
    { name: "8", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen05.1/main/47/إرشاد الساري لشرح صحيح البخاري ، الجز 8.pdf" },
    { name: "9", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen05.1/main/47/إرشاد الساري لشرح صحيح البخاري ، الجز 9.pdf" },
    { name: "10", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen05.1/main/47/إرشاد الساري لشرح صحيح البخاري ، الجز 10.pdf" },
    { name: "11", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen05.1/main/47/إرشاد الساري لشرح صحيح البخاري ، الجز 11.pdf" },
    { name: "12", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen05.1/main/47/إرشاد الساري لشرح صحيح البخاري ، الجز 12.pdf" },
    { name: "13", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen05.1/main/47/إرشاد الساري لشرح صحيح البخاري ، الجز 13.pdf" },
    { name: "14", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen05.1/main/47/إرشاد الساري لشرح صحيح البخاري ، الجز 14.pdf" },
    { name: "15", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen05.1/main/47/إرشاد الساري لشرح صحيح البخاري ، الجز 15.pdf" }
],
            isDropdownOpen: false
        },
        { 
            name: "التمهيد لما في الموطأ من المعاني في الأسانيد في حديث رسول الله - ط مؤسسة الفرقان", 
            type: "multi",
            publisher: "مؤسسة الفرقان",
            language: "العربية",
            volumes: [
    { name: "00", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen05.1/main/52/00.pdf" },
    { name: "01", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen05.1/main/52/01.pdf" },
    { name: "02", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen05.1/main/52/02.pdf" },
    { name: "03", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen05.1/main/52/03.pdf" },
    { name: "04", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen05.1/main/52/04.pdf" },
    { name: "05", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen05.1/main/52/05.pdf" },
    { name: "06", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen05.1/main/52/06.pdf" },
    { name: "07", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen05.1/main/52/07.pdf" },
    { name: "08", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen05.1/main/52/08.pdf" },
    { name: "09", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen05.1/main/52/09.pdf" },
    { name: "10", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen05.1/main/52/10.pdf" },
    { name: "11", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen05.1/main/52/11.pdf" },
    { name: "12", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen05.1/main/52/12.pdf" },
    { name: "13", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen05.1/main/52/13.pdf" },
    { name: "14", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen05.1/main/52/14.pdf" },
    { name: "15", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen05.1/main/52/15.pdf" },
    { name: "16", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen05.1/main/52/16.pdf" },
    { name: "17", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen05.1/main/52/17.pdf" }
],
            isDropdownOpen: false
        },
        { 
            name: "فتح الباري - ط دار السلام", 
            type: "multi",
            publisher: "دار السلام",
            language: "العربية",
            volumes: [
    { name: "01", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen05.2/main/44/فتح الباري شرح صحيح البخاري – دار السلام، الرياض – جلد 01.pdf" },
    { name: "02", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen05.2/main/44/فتح الباري شرح صحيح البخاري – دار السلام، الرياض – جلد 02.pdf" },
    { name: "03", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen05.2/main/44/فتح الباري شرح صحيح البخاري – دار السلام، الرياض – جلد 03.pdf" },
    { name: "04", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen05.2/main/44/فتح الباري شرح صحيح البخاري – دار السلام، الرياض – جلد 04.pdf" },
    { name: "05", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen05.2/main/44/فتح الباري شرح صحيح البخاري – دار السلام، الرياض – جلد 05.pdf" },
    { name: "06", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen05.2/main/44/فتح الباري شرح صحيح البخاري – دار السلام، الرياض – جلد 06.pdf" },
    { name: "07", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen05.2/main/44/فتح الباري شرح صحيح البخاري – دار السلام، الرياض – جلد 07.pdf" },
    { name: "08", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen05.2/main/44/فتح الباري شرح صحيح البخاري – دار السلام، الرياض – جلد 08.pdf" },
    { name: "09", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen05.2/main/44/فتح الباري شرح صحيح البخاري – دار السلام، الرياض – جلد 09.pdf" },
    { name: "10", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen05.2/main/44/فتح الباري شرح صحيح البخاري – دار السلام، الرياض – جلد 10.pdf" },
    { name: "11", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen05.2/main/44/فتح الباري شرح صحيح البخاري – دار السلام، الرياض – جلد 11.pdf" },
    { name: "12", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen05.2/main/44/فتح الباري شرح صحيح البخاري – دار السلام، الرياض – جلد 12.pdf" },
    { name: "13", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen05.2/main/44/فتح الباري شرح صحيح البخاري – دار السلام، الرياض – جلد 13.pdf" },
    { name: "14", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen05.2/main/44/فتح الباري شرح صحيح البخاري – دار السلام، الرياض – جلد 14.pdf" },
    { name: "15", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen05.2/main/44/فتح الباري شرح صحيح البخاري – دار السلام، الرياض – جلد 15.pdf" }
],
            isDropdownOpen: false
        },
        { 
            name: "المعلم بفوائد مسلم", 
            type: "multi",
            publisher: "N/A",
            language: "العربية",
            volumes: [
    { name: "0", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen05.2/main/46/mfm0.pdf" },
    { name: "1", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen05.2/main/46/mfm1.pdf" },
    { name: "2", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen05.2/main/46/mfm2.pdf" },
    { name: "3", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen05.2/main/46/mfm3.pdf" }
],
            isDropdownOpen: false
        },
        { 
            name: "تحفة الأحوذي", 
            type: "multi",
            publisher: "دار الفكر",
            language: "العربية",
            volumes: [
    { name: "00", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen05.2/main/54/tasgt00.pdf" },
    { name: "01", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen05.2/main/54/tasgt01.pdf" },
    { name: "02", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen05.2/main/54/tasgt02.pdf" },
    { name: "03", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen05.2/main/54/tasgt03.pdf" },
    { name: "04", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen05.2/main/54/tasgt04.pdf" },
    { name: "05", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen05.2/main/54/tasgt05.pdf" },
    { name: "06", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen05.2/main/54/tasgt06.pdf" },
    { name: "07", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen05.2/main/54/tasgt07.pdf" },
    { name: "08", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen05.2/main/54/tasgt08.pdf" },
    { name: "09", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen05.2/main/54/tasgt09.pdf" },
    { name: "10", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen05.2/main/54/tasgt10.pdf" }
],
            isDropdownOpen: false
        },
        { 
            name: "فتح الباري - ط دار طيبة", 
            type: "multi",
            publisher: "دار طيبة",
            language: "العربية",
            volumes: [
    { name: "1", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen05.2/main/55/فتح الباری شرح صحیح بخاری (1).pdf" },
    { name: "2", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen05.2/main/55/فتح الباری شرح صحیح بخاری (2).pdf" },
    { name: "3", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen05.2/main/55/فتح الباری شرح صحیح بخاری (3).pdf" },
    { name: "4", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen05.2/main/55/فتح الباری شرح صحیح بخاری (4).pdf" },
    { name: "5", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen05.2/main/55/فتح الباری شرح صحیح بخاری (5).pdf" },
    { name: "6", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen05.2/main/55/فتح الباری شرح صحیح بخاری (6).pdf" },
    { name: "7", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen05.2/main/55/فتح الباری شرح صحیح بخاری (7).pdf" },
    { name: "8", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen05.2/main/55/8فتح الباری شرح صحیح بخاری.pdf" },
    { name: "9", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen05.2/main/55/فتح الباری شرح صحیح بخاری (9).pdf" },
    { name: "10", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen05.2/main/55/فتح الباری شرح صحیح بخاری (10).pdf" },
    { name: "11", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen05.2/main/55/11_2032.pdf" }
],
            isDropdownOpen: false
        },
        { 
            name: "التمهيد لما في الموطأ من المعاني في الأسانيد في حديث رسول الله", 
            type: "multi",
            publisher: "N/A",
            language: "العربية",
            volumes: [
    { name: "00", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen06.2/main/53/ta_bar00.pdf" },
    { name: "01", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen06.2/main/53/ta_bar01.pdf" },
    { name: "02", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen06.2/main/53/ta_bar02.pdf" },
    { name: "03", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen06.2/main/53/ta_bar03.pdf" },
    { name: "04", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen06.2/main/53/ta_bar04.pdf" },
    { name: "05", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen06.2/main/53/ta_bar05.pdf" },
    { name: "06", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen06.2/main/53/ta_bar06.pdf" },
    { name: "07", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen06.2/main/53/ta_bar07.pdf" },
    { name: "08", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen06.2/main/53/ta_bar08.pdf" },
    { name: "09", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen06.2/main/53/ta_bar09.pdf" },
    { name: "10", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen06.2/main/53/ta_bar10.pdf" },
    { name: "11", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen06.2/main/53/ta_bar11.pdf" },
    { name: "12", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen06.2/main/53/ta_bar12.pdf" },
    { name: "13", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen06.2/main/53/ta_bar13.pdf" },
    { name: "14", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen06.2/main/53/ta_bar14.pdf" },
    { name: "15", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen06.2/main/53/ta_bar15.pdf" },
    { name: "16", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen06.2/main/53/ta_bar16.pdf" },
    { name: "17", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen06.2/main/53/ta_bar17.pdf" },
    { name: "18", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen06.2/main/53/ta_bar18.pdf" },
    { name: "19", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen06.2/main/53/ta_bar19.pdf" },
    { name: "20", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen06.2/main/53/ta_bar20.pdf" },
    { name: "21", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen06.2/main/53/ta_bar21.pdf" },
    { name: "22", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen06.2/main/53/ta_bar22.pdf" },
    { name: "23", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen06.2/main/53/ta_bar23.pdf" },
    { name: "24", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen06.2/main/53/ta_bar24.pdf" },
    { name: "25", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen06.2/main/53/ta_bar25.pdf" },
    { name: "26", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen06.2/main/53/ta_bar26.pdf" }
],
            isDropdownOpen: false
        },
        { 
            name: "إرشاد الساري شرح صحيح البخاري - ط ابن حزم", 
            type: "multi",
            publisher: "دار ابن حزم",
            language: "العربية",
            volumes: [
    { name: "1", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen06.2/main/51/إرشاد_الساري_ط_عطاءات_العلم_ج1_غير_ملون.pdf" },
    { name: "2", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen06.2/main/51/إرشاد_الساري_ط_عطاءات_العلم_ج2_غير_ملون.pdf" },
    { name: "3", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen06.2/main/51/إرشاد_الساري_ط_عطاءات_العلم_ج3_غير_ملون.pdf" },
    { name: "4", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen06.2/main/51/إرشاد_الساري_ط_عطاءات_العلم_ج4_غير_ملون.pdf" },
    { name: "5", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen06.2/main/51/إرشاد_الساري_ط_عطاءات_العلم_ج5_غير_ملون.pdf" },
    { name: "6", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen06.2/main/51/إرشاد_الساري_ط_عطاءات_العلم_ج6_غير_ملون.pdf" },
    { name: "7", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen06.2/main/51/إرشاد_الساري_ط_عطاءات_العلم_ج7_غير_ملون.pdf" },
    { name: "8", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen06.2/main/51/إرشاد_الساري_ط_عطاءات_العلم_ج8_غير_ملون.pdf" },
    { name: "9", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen06.2/main/51/إرشاد_الساري_ط_عطاءات_العلم_ج9_غير_ملون.pdf" },
    { name: "10", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen06.2/main/51/إرشاد_الساري_ط_عطاءات_العلم_ج10_غير_ملون.pdf" },
    { name: "11", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen06.2/main/51/إرشاد_الساري_ط_عطاءات_العلم_ج11_غير_ملون.pdf" },
    { name: "12", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen06.2/main/51/إرشاد_الساري_ط_عطاءات_العلم_ج12_غير_ملون.pdf" },
    { name: "13", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen06.2/main/51/إرشاد_الساري_ط_عطاءات_العلم_ج13_غير_ملون.pdf" },
    { name: "14", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen06.2/main/51/إرشاد_الساري_ط_عطاءات_العلم_ج14_غير_ملون.pdf" },
    { name: "15", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen06.2/main/51/إرشاد_الساري_ط_عطاءات_العلم_ج15_غير_ملون.pdf" },
    { name: "16", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen06.2/main/51/إرشاد_الساري_ط_عطاءات_العلم_ج16_غير_ملون.pdf" },
    { name: "17", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen06.2/main/51/إرشاد_الساري_ط_عطاءات_العلم_ج17_غير_ملون.pdf" },
    { name: "18", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen06.2/main/51/إرشاد_الساري_ط_عطاءات_العلم_ج18_غير_ملون.pdf" },
    { name: "19", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen06.2/main/51/إرشاد_الساري_ط_عطاءات_العلم_ج19_غير_ملون.pdf" },
    { name: "20", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen06.2/main/51/إرشاد_الساري_ط_عطاءات_العلم_ج20_غير_ملون.pdf" }
],
            isDropdownOpen: false
        },
        {
            name:"مرقاة المفاتيح شرح مشكاة المصابيح ",
            type:"multi",
            punlisher:"دار الفكر",
            language:"العربية",
           volumes: [
    { name: "01", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen04/main/43/01_67436.pdf" },
    { name: "02", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen04/main/43/02_67437.pdf" },
    { name: "03", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen04/main/43/03_67438.pdf" },
    { name: "04", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen04/main/43/04_67439.pdf" },
    { name: "05", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen04/main/43/05_67440.pdf" },
    { name: "06", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen04/main/43/06_67441.pdf" },
    { name: "07", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen04/main/43/07_67442.pdf" },
    { name: "08", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen04/main/43/08_67443.pdf" },
    { name: "09", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen04/main/43/09_67444.pdf" },
    { name: "10", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen04/main/43/10_67445.pdf" },
    { name: "11", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen04/main/43/11_67446.pdf" }
],
            isDropdownOpen: false
        },
        { 
            name: "تاريخ مدينة دمشق، تاريخ ابن عساكر", 
            type: "multi",
            publisher: "دار الفكر",
            language: "العربية",
            volumes: [
    { name: "00", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen07/main/65/00.pdf" },
    { name: "01", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen07/main/65/01.pdf" },
    { name: "01p", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen07/main/65/01p.pdf" },
    { name: "02", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen07/main/65/02.pdf" },
    { name: "03", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen07/main/65/03.pdf" },
    { name: "04", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen07/main/65/04.pdf" },
    { name: "05", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen07/main/65/05.pdf" },
    { name: "06", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen07/main/65/06.pdf" },
    { name: "07", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen07/main/65/07.pdf" },
    { name: "08", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen07/main/65/08.pdf" },
    { name: "09", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen07/main/65/09.pdf" },
    { name: "10", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen07/main/65/10.pdf" },
    { name: "11", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen07/main/65/11.pdf" },
    { name: "12", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen07/main/65/12.pdf" },
    { name: "13", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen07/main/65/13.pdf" },
    { name: "14", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen07/main/65/14.pdf" },
    { name: "15", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen07/main/65/15.pdf" },
    { name: "16", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen07/main/65/16.pdf" },
    { name: "17", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen07/main/65/17.pdf" },
    { name: "18", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen07/main/65/18.pdf" },
    { name: "19", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen07/main/65/19.pdf" },
    { name: "20", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen07/main/65/20.pdf" },
    { name: "21", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen07/main/65/21.pdf" },
    { name: "22", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen07/main/65/22.pdf" },
    { name: "23", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen07/main/65/23.pdf" },
    { name: "24", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen07/main/65/24.pdf" },
    { name: "25", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen07/main/65/25.pdf" },
    { name: "26", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen07/main/65/26.pdf" },
    { name: "27", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen07/main/65/27.pdf" },
    { name: "28", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen07/main/65/28.pdf" },
    { name: "29", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen07/main/65/29.pdf" },
    { name: "30", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen07/main/65/30.pdf" },
    { name: "31", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen07/main/65/31.pdf" },
    { name: "32", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen07/main/65/32.pdf" },
    { name: "33", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen07/main/65/33.pdf" },
    { name: "34", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen07/main/65/34.pdf" },
    { name: "35", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen07/main/65/35.pdf" },
    { name: "36", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen07/main/65/36.pdf" },
    { name: "37", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen07/main/65/37.pdf" },
    { name: "38", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen07/main/65/38.pdf" },
    { name: "39", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen07/main/65/39.pdf" },
    { name: "40", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen07/main/65/40.pdf" },
    { name: "41", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen07/main/65/41.pdf" },
    { name: "42", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen07/main/65/42.pdf" },
    { name: "43", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen07/main/65/43.pdf" },
    { name: "44", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen07/main/65/44.pdf" },
    { name: "45", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen07/main/65/45.pdf" },
    { name: "46", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen07/main/65/46.pdf" },
    { name: "47", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen07/main/65/47.pdf" },
    { name: "48", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen07/main/65/48.pdf" },
    { name: "49", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen07/main/65/49.pdf" },
    { name: "50", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen07/main/65/50.pdf" },
    { name: "51", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen07/main/65/51.pdf" },
    { name: "52", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen07/main/65/52.pdf" },
    { name: "53", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen07/main/65/53.pdf" },
    { name: "54", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen07/main/65/54.pdf" },
    { name: "55", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen07/main/65/55.pdf" },
    { name: "56", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen07/main/65/56.pdf" },
    { name: "57", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen07/main/65/57.pdf" },
    { name: "58", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen07/main/65/58.pdf" },
    { name: "59", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen07/main/65/59.pdf" },
    { name: "60", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen07/main/65/60.pdf" },
    { name: "61", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen07/main/65/61.pdf" },
    { name: "62", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen07/main/65/62.pdf" },
    { name: "63", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen07/main/65/63.pdf" },
    { name: "64", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen07/main/65/64.pdf" },
    { name: "65", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen07/main/65/65.pdf" },
    { name: "66", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen07/main/65/66.pdf" },
    { name: "67", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen07/main/65/67.pdf" },
    { name: "68", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen07/main/65/68.pdf" },
    { name: "69", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen07/main/65/69.pdf" },
    { name: "70", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen07/main/65/70.pdf" },
    { name: "71", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen07/main/65/71.pdf" },
    { name: "72", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen07/main/65/72.pdf" },
    { name: "73", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen07/main/65/73.pdf" },
    { name: "74", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen07/main/65/74.pdf" },
    { name: "75", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen07/main/65/75.pdf" },
    { name: "76", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen07/main/65/76.pdf" },
    { name: "77-78", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen07/main/65/77-78.pdf" },
    { name: "79p", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen07/main/65/79p.pdf" },
    { name: "79-80", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen07/main/65/79-80.pdf" }
],
            isDropdownOpen: false
        },
        { 
            name: "تهذيب الكمال في أسماء الرجال", 
            type: "multi",
            publisher: "مؤسسة الرسالة",
            language: "العربية",
           volumes: [
    { name: "00", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen07/main/66/tkar00.pdf" },
    { name: "01", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen07/main/66/tkar01.pdf" },
    { name: "02", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen07/main/66/tkar02.pdf" },
    { name: "03", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen07/main/66/tkar03.pdf" },
    { name: "04", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen07/main/66/tkar04.pdf" },
    { name: "05", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen07/main/66/tkar05.pdf" },
    { name: "06", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen07/main/66/tkar06.pdf" },
    { name: "07", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen07/main/66/tkar07.pdf" },
    { name: "08", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen07/main/66/tkar08.pdf" },
    { name: "09", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen07/main/66/tkar09.pdf" },
    { name: "10", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen07/main/66/tkar10.pdf" },
    { name: "11", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen07/main/66/tkar11.pdf" },
    { name: "12", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen07/main/66/tkar12.pdf" },
    { name: "13", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen07/main/66/tkar13.pdf" },
    { name: "14", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen07/main/66/tkar14.pdf" },
    { name: "15", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen07/main/66/tkar15.pdf" },
    { name: "16", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen07/main/66/tkar16.pdf" },
    { name: "17", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen07/main/66/tkar17.pdf" },
    { name: "18", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen07/main/66/tkar18.pdf" },
    { name: "19", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen07/main/66/tkar19.pdf" },
    { name: "20", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen07/main/66/tkar20.pdf" },
    { name: "21", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen07/main/66/tkar21.pdf" },
    { name: "22", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen07/main/66/tkar22.pdf" },
    { name: "23", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen07/main/66/tkar23.pdf" },
    { name: "24", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen07/main/66/tkar24.pdf" },
    { name: "25", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen07/main/66/tkar25.pdf" },
    { name: "26", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen07/main/66/tkar26.pdf" },
    { name: "27", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen07/main/66/tkar27.pdf" },
    { name: "28", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen07/main/66/tkar28.pdf" },
    { name: "29", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen07/main/66/tkar29.pdf" },
    { name: "30", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen07/main/66/tkar30.pdf" },
    { name: "31", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen07/main/66/tkar31.pdf" },
    { name: "32", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen07/main/66/tkar32.pdf" },
    { name: "33", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen07/main/66/tkar33.pdf" },
    { name: "34", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen07/main/66/tkar34.pdf" },
    { name: "35", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen07/main/66/tkar35.pdf" }
],
            isDropdownOpen: false
        },
        { 
            name: "المنهاج شرح صحيح ملسم للنووي", 
            type: "multi",
            publisher: "دار أحياء التارث العربي",
            language: "العربية",
            volumes: [
    { name: "00", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen06.1/main/48/shsm00.pdf" },
    { name: "01", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen06.1/main/48/shsm01.pdf" },
    { name: "02", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen06.1/main/48/shsm02.pdf" },
    { name: "03", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen06.1/main/48/shsm03.pdf" },
    { name: "04", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen06.1/main/48/shsm04.pdf" },
    { name: "05", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen06.1/main/48/shsm05.pdf" },
    { name: "06", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen06.1/main/48/shsm06.pdf" },
    { name: "07", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen06.1/main/48/shsm07.pdf" },
    { name: "08", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen06.1/main/48/shsm08.pdf" },
    { name: "09", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen06.1/main/48/shsm09.pdf" },
    { name: "10", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen06.1/main/48/shsm10.pdf" },
    { name: "11", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen06.1/main/48/shsm11.pdf" },
    { name: "12", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen06.1/main/48/shsm12.pdf" },
    { name: "13", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen06.1/main/48/shsm13.pdf" },
    { name: "14", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen06.1/main/48/shsm14.pdf" },
    { name: "15", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen06.1/main/48/shsm15.pdf" },
    { name: "16", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen06.1/main/48/shsm16.pdf" },
    { name: "17", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen06.1/main/48/shsm17.pdf" },
    { name: "18", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen06.1/main/48/shsm18.pdf" }
],
            isDropdownOpen: false
        },
        { 
            name: "عمدة القاري شرح صحيح البخاري", 
            type: "multi",
            publisher: "دار الفكر",
            language: "العربية",
            volumes: [
    { name: "00", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen06.1/main/50/00.pdf" },
    { name: "01a", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen06.1/main/50/01a.pdf" },
    { name: "02", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen06.1/main/50/02.pdf" },
    { name: "03", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen06.1/main/50/03.pdf" },
    { name: "04", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen06.1/main/50/04.pdf" },
    { name: "05", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen06.1/main/50/05.pdf" },
    { name: "06", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen06.1/main/50/06.pdf" },
    { name: "07", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen06.1/main/50/07.pdf" },
    { name: "08", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen06.1/main/50/08.pdf" },
    { name: "09", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen06.1/main/50/09.pdf" },
    { name: "10", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen06.1/main/50/10.pdf" },
    { name: "11", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen06.1/main/50/11.pdf" },
    { name: "12", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen06.1/main/50/12.pdf" },
    { name: "13", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen06.1/main/50/13.pdf" },
    { name: "14", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen06.1/main/50/14.pdf" },
    { name: "15", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen06.1/main/50/15.pdf" },
    { name: "16", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen06.1/main/50/16.pdf" },
    { name: "17", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen06.1/main/50/17.pdf" },
    { name: "18", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen06.1/main/50/18.pdf" },
    { name: "19", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen06.1/main/50/19.pdf" },
    { name: "20", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen06.1/main/50/20.pdf" },
    { name: "21", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen06.1/main/50/21.pdf" },
    { name: "22", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen06.1/main/50/22.pdf" },
    { name: "23", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen06.1/main/50/23.pdf" },
    { name: "24", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen06.1/main/50/24.pdf" },
    { name: "25", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen06.1/main/50/25.pdf" },
    { name: "1b", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen06.1/main/50/1.pdf" }
],
            isDropdownOpen: false
        },
        { 
            name: "سبل السلام الموصلة الى بلوغ المرام.", 
            type: "multi",
            publisher: "دار ابن الجوزي ",
            language: "العربية",
            volumes: [
    { name: "01", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen06.1/main/56/01.pdf" },
    { name: "02", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen06.1/main/56/02.pdf" },
    { name: "03", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen06.1/main/56/03.pdf" },
    { name: "04", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen06.1/main/56/04.pdf" },
    { name: "05", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen06.1/main/56/05.pdf" },
    { name: "06", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen06.1/main/56/06.pdf" },
    { name: "07", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen06.1/main/56/07.pdf" },
    { name: "08", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen06.1/main/56/08.pdf" }
],
            isDropdownOpen: false
        },
        { 
            name: "كتاب العلل ومعرفة الرجال", 
            type: "multi",
            publisher: "دار الخاني",
            language: "العربية",
            volumes: [
    { name: "0", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen06.1/main/57/emra0.pdf" },
    { name: "1", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen06.1/main/57/emra1.pdf" },
    { name: "2", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen06.1/main/57/emra2.pdf" },
    { name: "3", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen06.1/main/57/emra3.pdf" },
    { name: "4", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen06.1/main/57/emra4.pdf" }
],
            isDropdownOpen: false
        },
        { 
            name: "التاريخ الكبير للبخاري", 
            type: "multi",
            publisher: "دار الكتب العلمية",
            language: "العربية",
            volumes: [
    { name: "01", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen06.1/main/58/التاريخ الكبير - أبو عبد الله محمد بن إسماعيل البخاري (المتوفى 256هـ) دار الكتب العلمية، بیروت – جلد 01.pdf" },
    { name: "02", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen06.1/main/58/التاريخ الكبير - أبو عبد الله محمد بن إسماعيل البخاري (المتوفى 256هـ) دار الكتب العلمية، بیروت – جلد 02.pdf" },
    { name: "03", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen06.1/main/58/التاريخ الكبير - أبو عبد الله محمد بن إسماعيل البخاري (المتوفى 256هـ) دار الكتب العلمية، بیروت – جلد 03.pdf" },
    { name: "04", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen06.1/main/58/التاريخ الكبير - أبو عبد الله محمد بن إسماعيل البخاري (المتوفى 256هـ) دار الكتب العلمية، بیروت – جلد 04.pdf" },
    { name: "05", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen06.1/main/58/التاريخ الكبير - أبو عبد الله محمد بن إسماعيل البخاري (المتوفى 256هـ) دار الكتب العلمية، بیروت – جلد 05.pdf" },
    { name: "06", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen06.1/main/58/التاريخ الكبير - أبو عبد الله محمد بن إسماعيل البخاري (المتوفى 256هـ) دار الكتب العلمية، بیروت – جلد 06.pdf" },
    { name: "07", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen06.1/main/58/التاريخ الكبير - أبو عبد الله محمد بن إسماعيل البخاري (المتوفى 256هـ) دار الكتب العلمية، بیروت – جلد 07.pdf" },
    { name: "08", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen06.1/main/58/التاريخ الكبير - أبو عبد الله محمد بن إسماعيل البخاري (المتوفى 256هـ) دار الكتب العلمية، بیروت – جلد 08.pdf" },
    { name: "09", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen06.1/main/58/التاريخ الكبير - أبو عبد الله محمد بن إسماعيل البخاري (المتوفى 256هـ) دار الكتب العلمية، بیروت – جلد 09.pdf" }
],
            isDropdownOpen: false
        },
        { 
            name: "كتاب المجروحين لابن حبان", 
            type: "multi",
            publisher: "N/A",
            language: "العربية",
            volumes: [
    { name: "01", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen06.1/main/59/01_44014.pdf" },
    { name: "02", file: "https://raw.githubusercontent.com/saadhusainn/sijjeen06.1/main/59/02_44015.pdf" }
],
            isDropdownOpen: false
        }
    ]
};
